faiss_index:
  path: colorfact/vector_store/faiss_index.idx

all_products_dataset:
  path: colorfact/data/data_preview.xlsx

ontologie:
  path: colorfact/configs/outfit.yaml
  
mapping_json_file:
  path: colorfact/mapping/product_mapping.json

image_vision_model:
  llm: gpt-4o
  llm_temperature: 0.0
  prompt: ""
